# Generated by Django 5.1.5 on 2025-02-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_verifysuccessfulemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='verifysuccessfulemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
