# Generated by Django 5.1.5 on 2025-02-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_groupmodel_permissonmodel_assigngrouppermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifySuccessfulEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assigngrouppermission',
            name='group',
            field=models.ManyToManyField(to='account.groupmodel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='permission',
            field=models.ManyToManyField(to='account.permissonmodel'),
        ),
    ]
