# Generated by Django 5.1.5 on 2025-02-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_groupmodel_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('otp', models.IntegerField()),
                ('expire_time', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountTestModel',
        ),
    ]
