# Generated by Django 5.1.3 on 2025-01-29 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_assigngrouppermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigngrouppermission',
            name='permission',
        ),
        migrations.AlterField(
            model_name='assigngrouppermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='permission',
        ),
        migrations.AddField(
            model_name='assigngrouppermission',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, related_name='permissions', to='account.permissonmodel'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='account.permissonmodel'),
        ),
    ]
