# Generated by Django 5.1.3 on 2025-01-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_assigngrouppermission_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigngrouppermission',
            name='permission',
            field=models.ManyToManyField(related_name='permissions', to='account.permissonmodel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='permission',
            field=models.ManyToManyField(to='account.permissonmodel'),
        ),
    ]
