# Generated by Django 5.1.5 on 2025-02-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_customuser_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='club',
        ),
    ]
