# Generated by Django 5.1.3 on 2025-01-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_groupmodel_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigngrouppermission',
            name='group',
            field=models.ManyToManyField(related_name='group', to='account.groupmodel'),
        ),
        migrations.AlterField(
            model_name='assigngrouppermission',
            name='permission',
            field=models.ManyToManyField(related_name='permission', to='account.permissonmodel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='permission',
            field=models.ManyToManyField(related_name='group', to='account.permissonmodel'),
        ),
    ]
