# Generated by Django 5.1.3 on 2025-01-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_assigngrouppermission_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigngrouppermission',
            name='permission',
        ),
    ]
