version: '3.8'

services:
  web:
    environment:
      - DJANGO_ENV=production
    build: 
        context: .
        dockerfile: "docker/django/Dockerfile"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  celery:
    environment:
      - DJANGO_ENV=production 
    build: 
        context: .
        dockerfile: "docker/django/Dockerfile"
    command: celery -A config.celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
      - web

  celery-beat:
    environment:
      - DJANGO_ENV=production 
    build: 
        context: .
        dockerfile: "docker/django/Dockerfile"
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
      - web

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  postgres_data:
