# Generated by Django 5.1.5 on 2025-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_code_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='category',
        ),
        migrations.AddField(
            model_name='promocode',
            name='category',
            field=models.ManyToManyField(to='promo_code_app.promocodecategory'),
        ),
    ]
