# Generated by Django 5.1.5 on 2025-01-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttypechoice',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='employment_type_choice_club', to='club.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutename',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='institution_name_club', to='club.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipstatuschoice',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='membership_status_choice_club', to='club.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='membership_type_club', to='club.club'),
            preserve_default=False,
        ),
    ]
