# Generated by Django 5.1.5 on 2025-02-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employmenttypechoice_club_institutename_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenttypechoice',
            name='club',
        ),
        migrations.RemoveField(
            model_name='institutename',
            name='club',
        ),
        migrations.RemoveField(
            model_name='membershipstatuschoice',
            name='club',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='club',
        ),
    ]
