# Generated by Django 5.1.5 on 2025-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employmenttypechoice_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutename',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
