# Generated by Django 5.1.5 on 2025-05-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_institutename_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutename',
            name='code',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
    ]
