# Generated by Django 5.1.5 on 2025-04-07 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0015_alter_spouse_is_active'),
        ('member_financial_management', '0001_initial'),
        ('product', '0001_initial'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='products',
            field=models.ManyToManyField(related_name='invoice_item_products', to='product.product'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='restaurant_items',
            field=models.ManyToManyField(related_name='restaurant_items', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_type', to='member_financial_management.invoicetype'),
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_account_member', to='member.member'),
        ),
        migrations.AddField(
            model_name='memberdue',
            name='due_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_due_due_reference', to='member_financial_management.due'),
        ),
        migrations.AddField(
            model_name='memberdue',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_due_member', to='member.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_invoice', to='member_financial_management.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_member', to='member.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_processed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='due',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_payment', to='member_financial_management.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_payment_method', to='member_financial_management.paymentmethod'),
        ),
        migrations.AddField(
            model_name='income',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_received_by', to='member_financial_management.paymentmethod'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_customer', to='member.member'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoice', to='member_financial_management.invoice'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_method', to='member_financial_management.paymentmethod'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_source', to='member_financial_management.saletype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_invoice', to='member_financial_management.invoice'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_member', to='member.member'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_payment_method', to='member_financial_management.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='member_financial_management.transaction'),
        ),
        migrations.AddField(
            model_name='due',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_transaction', to='member_financial_management.transaction'),
        ),
    ]
