# Generated by Django 5.1.5 on 2025-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_financial_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
