# Generated by Django 5.1.5 on 2025-04-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_financial_management', '0003_alter_payment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='income',
            name='sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='income_sale', to='member_financial_management.sale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='discount_applied',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
