# Generated by Django 5.1.5 on 2025-04-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_financial_management', '0005_alter_memberaccount_overdue_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='discount_applied',
        ),
    ]
