# Generated by Django 5.1.5 on 2025-04-17 04:31

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_financial_management', '0006_remove_income_discount_applied'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='memberdue',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentmethod',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='due',
            name='is_due_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberdue',
            name='is_due_paid',
            field=models.BooleanField(default=False),
        ),
    ]
