# Generated by Django 5.1.5 on 2025-04-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_financial_management', '0007_alter_memberdue_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='excel_upload_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
