# Generated by Django 5.1.5 on 2025-08-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_financial_management', '0008_invoice_excel_upload_date'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='restaurant_items',
            field=models.ManyToManyField(related_name='invoice_item_restaurants', to='restaurant.restaurantitem'),
        ),
    ]
