from django.urls import path
from . import views
urlpatterns = [
    path("v1/payment/options/", views.PaymentMethodView.as_view(),
         name="payment_options_view"),
    path("v1/payment/invoice/", views.InvoicePaymentView.as_view(),
         name="invoice_payment_view"),
    path("v1/income/particular/", views.IncomeParticularView.as_view(),
         name="income_particular_view"),
    path("v1/income/", views.IncomeView.as_view(),
         name="income_view"),
    path("v1/income/<int:id>/", views.IncomeSpecificView.as_view(),
         name="income_specific_view"),
    path("v1/income/receiving_options/", views.IncomeReceivedFromView.as_view(),
         name="income_receiving_option_view"),
    path("v1/invoices/", views.InvoiceShowView.as_view(),
         name="invoice_show_view"),
    path("v1/invoices/<int:id>/", views.InvoiceSpecificView.as_view(),
         name="invoice_specific_view"),
    path("v1/sales/", views.SalesView.as_view(),
         name="sales_view"),
    path("v1/sales/<int:id>/", views.SalesSpecificView.as_view(),
         name="sales_specific_view"),
    path("v1/transactions/", views.TransactionView.as_view(),
         name="transaction_view"),
    path("v1/transactions/<int:id>/", views.TransactionSpecificView.as_view(),
         name="transaction_specific_view"),
    path("v1/payments/", views.PaymentView.as_view(),
         name="payment_view"),
    path("v1/payments/<int:id>/", views.PaymentSpecificView.as_view(),
         name="payment_specific_view"),
    path("v1/dues/", views.DueView.as_view(),
         name="dues_view"),
    path("v1/dues/<int:id>/", views.DueSpecificView.as_view(),
         name="dues_specific_view"),
    path("v1/member_dues/", views.MemberDueView.as_view(),
         name="member_dues_view"),
    path("v1/member_dues/<int:id>/", views.MemberDueSpecificView.as_view(),
         name="member_due_specific_view"),
    path("v1/member_accounts/recharge/", views.MemberAccountRechargeView.as_view(),
         name="member_account_recharge_view"),
    path("v1/member_accounts/", views.MemberAccountView.as_view(),
         name="member_account_view"),
    path("v1/member_accounts/<str:id>/", views.MemberAccountSpecificSpecificView.as_view(),
         name="member_accounts_specific_view"),
    
    
]
