# Generated by Django 5.1.5 on 2025-01-30 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersfinancialbasics',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='member_financial_basics_club', to='club.club'),
            preserve_default=False,
        ),
    ]
