# Generated by Django 5.1.5 on 2025-02-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_membersfinancialbasics_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='club',
        ),
        migrations.RemoveField(
            model_name='membersfinancialbasics',
            name='club',
        ),
    ]
