# Generated by Django 5.1.5 on 2025-02-17 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employmenttypechoice_club_and_more'),
        ('member', '0004_addresstypechoice_contacttypechoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='address_type_choice', to='core.addresstypechoice'),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='contact_type',
            field=models.ForeignKey(default='present', on_delete=django.db.models.deletion.RESTRICT, related_name='contact_type_choice', to='core.contacttypechoice'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='descendant_relation_choice', to='core.descendantrelationchoice'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_type_choice', to='core.documenttypechoice'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='email_type_choice', to='core.emailtypechoice'),
        ),
        migrations.DeleteModel(
            name='EmploymentTypeChoice',
        ),
        migrations.DeleteModel(
            name='AddressTypeChoice',
        ),
        migrations.DeleteModel(
            name='ContactTypeChoice',
        ),
        migrations.DeleteModel(
            name='DescendantRelationChoice',
        ),
        migrations.DeleteModel(
            name='DocumentTypeChoice',
        ),
        migrations.DeleteModel(
            name='EmailTypeChoice',
        ),
    ]
