# Generated by Django 5.1.5 on 2025-02-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employmenttypechoice_club_and_more'),
        ('member', '0005_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouse',
            name='current_status',
            field=models.ForeignKey(default='present', on_delete=django.db.models.deletion.RESTRICT, related_name='spouse_current_status', to='core.spousestatuschoice'),
        ),
        migrations.DeleteModel(
            name='SpouseStatusChoice',
        ),
    ]
