# Generated by Django 5.1.5 on 2025-02-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_availableid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_ID',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
