# Generated by Django 5.1.5 on 2025-02-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_member_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('transferred', models.BooleanField(default=False)),
                ('transferred_reason', models.TextField(blank=True, default='', null=True)),
                ('stored_member_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history', to='member.member')),
            ],
        ),
    ]
