# Generated by Django 5.1.5 on 2025-02-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employmenttypechoice_club_and_more'),
        ('member', '0011_alter_contactnumber_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='address_type_choice', to='core.addresstypechoice'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companioninformation',
            name='companion_card_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companioninformation',
            name='companion_contact_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companioninformation',
            name='companion_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='companion_images/'),
        ),
        migrations.AlterField(
            model_name='companioninformation',
            name='relation_with_member',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='contact_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contact_type_choice', to='core.contacttypechoice'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='descendant_contact_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='descendant_images/'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='relation_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='descendant_relation_choice', to='core.descendantrelationchoice'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='email_type_choice', to='core.emailtypechoice'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation_with_member',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='current_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='spouse_current_status', to='core.spousestatuschoice'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='spouse_images/'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='spouse_contact_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='AvailableID',
        ),
    ]
