# Generated by Django 5.1.5 on 2025-02-20 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employmenttypechoice_club_and_more'),
        ('member', '0012_alter_address_address_type_alter_address_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='member_gender', to='core.gender'),
            preserve_default=False,
        ),
    ]
