# Generated by Django 5.1.5 on 2025-04-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_alter_spouse_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
