# Generated by Django 5.1.5 on 2025-09-21 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_spouse_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberhistory',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='history', to='member.member'),
        ),
        migrations.AlterField(
            model_name='memberhistory',
            name='stored_member_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
