# Generated by Django 5.1.5 on 2025-06-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_singleemail_emailgroup_emaillist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailgroup',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='provider',
            field=models.CharField(choices=[('gmail', 'gmail'), ('personal', 'Personal Domain'), ('ses', 'Amazon SES')], default='gmail', max_length=50),
        ),
    ]
