# Generated by Django 5.1.5 on 2025-06-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_alter_emailgroup_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillist',
            name='full_name',
        ),
    ]
