# Generated by Django 5.1.5 on 2025-06-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_remove_emaillist_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField(blank=True, default=None)),
                ('notes', models.TextField(blank=True, default='')),
                ('email_compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_compose_sends', to='mails.email_compose')),
                ('group', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='email_group_sends', to='mails.emailgroup')),
                ('single_email', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='email_single_sends', to='mails.singleemail')),
            ],
        ),
    ]
