# Generated by Django 5.1.5 on 2025-06-25 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_remove_emaillist_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='email_compose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_compose_attachments', to='mails.email_compose'),
        ),
        migrations.RenameModel(
            old_name='Email_Compose',
            new_name='EmailCompose',
        ),
        migrations.CreateModel(
            name='EmailSendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('email_compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_compose_sends', to='mails.emailcompose')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_group_sends', to='mails.emailgroup')),
                ('single_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_single_sends', to='mails.singleemail')),
            ],
        ),
    ]
