# Generated by Django 5.1.5 on 2025-06-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_alter_emailattachment_email_compose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='email_compose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mails.emailcompose'),
        ),
    ]
