# Generated by Django 5.1.5 on 2025-06-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_emailsend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsend',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
