# Generated by Django 5.1.5 on 2025-06-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_alter_outbox_email_compose'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbox',
            name='is_from_template',
            field=models.BooleanField(default=False),
        ),
    ]
