# Generated by Django 5.1.5 on 2025-06-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_alter_emailsend_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsend',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_group_sends', to='mails.emailgroup'),
        ),
        migrations.AlterField(
            model_name='emailsend',
            name='single_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_single_sends', to='mails.singleemail'),
        ),
    ]
