# Generated by Django 5.1.5 on 2025-06-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_outbox_is_from_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='email_compose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_email_composes', to='mails.emailcompose'),
        ),
    ]
