# Generated by Django 5.1.5 on 2025-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0008_alter_outbox_email_compose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='emaillist',
            unique_together={('email', 'group')},
        ),
    ]
