# Generated by Django 5.1.5 on 2025-02-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
