# Generated by Django 5.1.5 on 2025-04-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_employmenttypechoice_club_and_more'),
        ('member', '0015_alter_spouse_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limit', models.IntegerField()),
                ('description', models.TextField()),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='promo_code_detail_membership_type', to='core.membershiptype')),
            ],
            options={
                'unique_together': {('promo_code', 'membership_type')},
            },
        ),
        migrations.CreateModel(
            name='AppliedPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applied_promo_code_member', to='member.member')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applied_promo_code_category', to='promo_code.promocodecategory')),
                ('promo_code_detail', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applied_promo_code', to='promo_code.promocodedetail')),
            ],
        ),
    ]
