# Generated by Django 5.1.5 on 2025-04-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_code', '0002_appliedpromocode_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocodecategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
