# Generated by Django 5.1.5 on 2025-04-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_code', '0003_rename_category_name_promocodecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodedetail',
            name='remaining_limit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
