name: Integration Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine # Lightweight version
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379 # Maps port 6379 on the service container to localhost:6379 on the runner

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "False"
      COOKIE_SECURE: "False"
      REDIS_URL_DEV: ${{ secrets.REDIS_URL_DEV }}
      REDIS_URL_PROD: ${{ secrets.REDIS_URL_PROD }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
